### ISSUE TITLE
Add Summaries

### ISSUE THREAD

**Issue by o1i** [NLU2017/nlu2017#14]
If we had a nice summary-writer, we could actually use Tensorboard to compare different runs, which would look nice.

**Comment by halungge** [comment]
I have added some summaries in a branch feature/tensorboard. (see pull request) By now tensorboard shows some scalars (loss, perplexity) and histograms. I don't know whether the histograms make sense as they are. It would make sense to further add the embedding, the learning rates and some distributions.
