### ISSUE TITLE
Something is wrong with the perplexity.

### ISSUE THREAD

**Issue by o1i** [NLU2017/nlu2017#15]
The values I get for perplexity are unreasonably low, yet I fail to see why.
Please see whether you can spot the error. (Or maybe I should really only average the sentence-perplexities instead of the losses, but the problem is about two orders of magnitude, so I guess that is not it).

**Comment by halungge** [comment]
Don't we need to to normalize to the effective length of each sentence in the perplexity calculation?
In the project description they say the <eos> is part of the sentence but the <pad> is not. Hence, if a sentence is shorter than 30 words, we should not divide by FLAGS.sentence_length but by the position of the <eos>
