### ISSUE TITLE
Data Duplication in the batch_iterator?

### ISSUE THREAD

**Issue by o1i** [NLU2017/nlu2017#7]
I have just recently learned about generators, so this is an honest question:
it looks as if inside the batch_iterator we would create a shuffled copy of the data (shuffled_data = data[...]). Is this copy physically created? If yes, I would rather just store the shuffled indexes instead and yield self.data[suffled_indexes[start:end]], as this would require less memory. If no: What are the rules when physical copies are created?

**Comment by halungge** [comment]
Hmm, good point, I don't know actually. 
I would guess that it really copies the data array, because the generator thingy only comes into play in the yield -- expression, right.

**Comment by halungge** [comment]
Here the claim that sub-indexing an array will only create a view of the original array.
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
which would makes much sense implementation wise..

**Comment by o1i** [comment]
wonderful, then we can assume this to be true and close the issue :)
